notaz/pcsx_rearmed

configure
* Update RPI vendor library names to allow compatibility with recent
firmwares that have obsoleted the originally named duplicate libraries.
* Add override to build against VC4 Mesa driver via "VIDEOCORE=no"
=> RPI: add Mesa override & update vendor library names

libpcsxcore/psxmem.c
Credits to @senquack for fixing the issue, i was just the one, well, pointing the issue as to why the game would crash hehehe. This is what he says about it :
> Fixes 'Tetris with Card Captor Sakura - Eternal Heart (Japan)' startup.
Thanks to gameblabla for finding this issue and pointing out that
Mednafen had a fix for it. It's adapted here in a much simpler form.
Patch basically sets all the bits on reads in the PIO memory area. With the fix in place, Tetris With Card Captor Sakura is now playable.
=> psxmem: Reads of PIO Expansion area read all-ones.

libpcsxcore/cdriso.c, plugins/cdrcimg/cdrcimg.c
When compiling PCSX_rearmed against newer versions of zlib, there's a conflict with uncompress2 since it also exists in zlib.
This allows PCSX_rearmed to compile, and it should also work against older zlib versions too.
=> Fix for compiling it against newer zlib versions.

libpcsxcore/gte.c
> Fix glitched drawing of road surface in 'Burning Road'..
> behavior now matches Mednafen. This also preserves the fix by Shalma
> from prior commit f916013 for missing elements in 'Legacy of Kain:
> Soul Reaver' (missing green plasma balls in first level).
> 
- backported fix from pcsx4all
https://github.com/dmitrysmagin/pcsx4all/pull/41/commits/a6ff7d29d615bdb26b491f4e1e2a9f4608a8d643
- fixes R4 - Ridge Racer Type 4 lighting issue
https://github.com/libretro/pcsx_rearmed/issues/216#event-2224076280
=> gte: backport fix for RTPS/RTPT

libpcsxcore/psxbios.c
- This is fixed by adding the missing SaveMcd() to buwrite().
Tested on Wild Arms and Breath of Fire III
=> Fix corrupted memory card saves when using HLE

plugins/gpulib/gpu.c
Fixes corrupted gfx in this PS1 .exe test utility:
https://github.com/PeterLemon/PSX/tree/master/CPUTest/CPU/LOADSTORE/LW
(This and almost all similar tests on Peter's site).
=> gpulib: fix out-of-bounds reads in do_cmd_buffer()

libpcsxcore/cdrom.c
For some Eboot .PBP game images, when loading a savestate, a zlib error
like 'uncompress failed with -5 for block 5383, sector 86132' would be
output to stdout/stderr. The savestate would still be playable, though.
Traced it down to cdrFreeze() failing to convert cdr.Prev from BCD->int
when calling ReadTrack(). Note that the odd 'cdr.Prev[0]++;' line seems
to be someone's hacky way of forcing ReadTrack() to avoid skipping what
it thinks is a duplicate sector read.
=> cdrom: add missing BCD->int convert in cdrFreeze()

frontend/cspace_neon.S
Already merged into libretro/pcsx_rearmed, not sure what the proper procedure is for sending it upstream to you. Let me know if there's a better way to do this!
tl;dr the neon version of bgr555_to_rgb565 wasn't discarding the MSB of the BGR color (used for transparency / masking elsewhere in the PSX) and as a result, the bit twiddling operations end up corrupting the green value.
See https://github.com/libretro/pcsx_rearmed/pull/405 for more details and screenshots.
=> Fixed bug where MSB of a 15-bit BGR color could corrupt green value.

libpcsxcore/cdrom.c
Fixes #101. Fast cd response causes the game to peek bad sectors and crash.
=> Fix crash on retrying mission in driver

libpcsxcore/psxdma.c, plugins/dfxvideo/gpu.c, plugins/gpu-gles/gpuPlugin.c
Taken from PCSX Redux project.
https://github.com/grumpycoders/pcsx-redux/pull/396/commits/a6401da3a4e7b4860b0f7a7f679cf9a93e739caa
According to the original Pull request post :
"LL DMA should end when the pointer of the next node has bit 23 set and not necessarily when it's 0xFF'FFFF"
I think i'm doing it right but i'm not sure what is affected by this.
=> Fixed Linked List DMA end marker.

libpcsxcore/gte.c, libpcsxcore/gte_divider.h
This came from https://github.com/jdgleaver/RG350_pcsx4all/commit/864de6772c35bbf4812d3a9a2d525b2da57d974d
Original comment by senquack :
"gteH register is u16, not s16. DIVIDE macro/func assumed it was
s16 for some reason. Behavior now matches Mednafen."
I'm surprised this wasn't merged back yet and it seems correct.
I also put in there the "GTE_USE_NATIVE_DIVIDE" stuff but currently unless manually enabled, it's not used.
=> gte: Fix gteH division and sign extension (from PCSX4ALL/senquack)

.gitmodules, Makefile, frontend/menu.c, libpcsxcore/cdriso.c
This adds CHD support to PCSX Rearmed based on the work of aliaspider for libretro's fork.
The only difference from it is that i'm implementing as a sub-module for maintenance reasons.
It's also not added to the configure script for now as i don't want it to conflict with pull request https://github.com/notaz/pcsx_rearmed/pull/187.
I'll add the option to enable CHD support once that PR is merged...
Or make CHD support mandatory. (but i'm not really willing to do that as on some really low end platforms, CHD support does have a performance/memory impact)
=> CHD support from libretro's fork.

Makefile, libpcsxcore/database.c, libpcsxcore/database.h, libpcsxcore/misc.c, libpcsxcore/sio.h
This adds an internal database for some problematic games, which for now only includes te memory card hack for Codename tenka. (The game will not work otherwise)
There's also a thin patch for Codename tenka so it works over HLE too.
This was tested on a PC and i could confirm it (finally) fixes Codename tenka.
Note that codename tenka also requires digital controls. I think i'll do a separate patch for those. Maybe...
=> Add internal database for problematic games

libpcsxcore/cdrom.c, libpcsxcore/cdrom.h
Upstreamed changes from PCSX Redux as seen here :
https://github.com/grumpycoders/pcsx-redux/commit/5730e04f0183f37038bc1d133cf9f9092425b90a
This apparently fixes Deus Fight in Xenogears.
"Slightly more accurate read delays after seeks.
Fixes Xenogears' Deus fight."
I've tried it with normal games and they didn't seem to be affected so far, at least negatively speaking.
=> CDRom timings changes

plugins/dfsound/registers.c
Fix is from PCSX-Redux :
https://github.com/grumpycoders/pcsx-redux/commit/4e905d7953a26bffd52f486dc5b03c2a19075d01
I have tested the fix against Loonies 8192 (a PSn00bSDK made homebrew game) and it no longer locks up during loading.
This affects all games and demos that uses PSn00bSDK. (I've been told it's unlikely this will affect games that uses the official SDK)
=> [SPU] Emulate SPUSTAT[5:0] as a mirror of SPUCNT[5:0]

libpcsxcore/psxbios.c
See PCSX-Redux's openbios :
https://github.com/grumpycoders/pcsx-redux/blob/93653ba5281487d3bed57371d7b64c32dfc669f0/src/mips/openbios/gpu/gpu.c
That +1 for size was really triggering me, haha... (Pointer is also u32, according to OpenBIOS)
The original source code was based upon the disassembly of the source code by a Japanese user.
=> Rewrite GPU bios functions according to OpenBIOS.

libpcsxcore/new_dynarec/emu_if.h, libpcsxcore/new_dynarec/new_dynarec.c, libpcsxcore/psxhle.c, libpcsxcore/psxhle.h, libpcsxcore/psxinterpreter.c
Fix is from PCSX-redux :
https://github.com/grumpycoders/pcsx-redux/commit/99c9508f2a9dc1444b88f37eb100cdfb17862b52
This should hopefully fix HDHOSHY's experimental patch properly.
I'm not so sure about my code for the dynarec however but it is a direct equivalent to the interpreter's.
One instance when this does happen is Nuclear Strike over HLE when attempting to load a save.
```
#0  0x0000555555595e55 in psxBranchNoDelay ()
at libpcsxcore/psxinterpreter.c:293
#1  0x00005555555962c9 in psxDelayBranchTest (tar1=160)
at libpcsxcore/psxinterpreter.c:369
#2  0x0000555555596386 in doBranch (tar=160)
at libpcsxcore/psxinterpreter.c:419
#3  0x00005555555977b4 in psxJR () at libpcsxcore/psxinterpreter.c:629
#4  0x00005555555981c2 in psxSPECIAL () at libpcsxcore/psxinterpreter.c:824
#5 …
```
=> Properly protect the HLE instructions against corrupted memory.

libpcsxcore/mdec.c
This based on an original fix by dmitrysmagin in PCSX4ALL.
He had this to say :
"This fixes graphic artifacts during cinematics in Vandal Hearts
and R-Types, other games seem to be unaffected. (?)
Need to test more, revert if problems."
I can confirm for me this fixes the graphical issues that happened during the videos in R-types.
People that used the PCSX4ALL fork that used this fix for a while did not seem to have encountered any regressions.
Setting it to 4 still doesn't fix the problem, it needs to be 6.
**Below : MDEC_BIAS set to 2**
**Below : MDEC_BIAS set to 6**
However, it turns out MDEC_BIAS set to 6 was still not enough for Galerians.
As said in https://github.com/notaz/pcsx_rearmed/issues/145, Galerians has the same issue but worse.
Setting to 6 makes it look like this
That …
=> mdec.cpp: Dare to set MDEC_BIAS to 10

libpcsxcore/cdrom.c
This was inspired by the fix in Duckstation :
https://github.com/stenzek/duckstation/commit/0710e3b6d384526ed939f742f8f657623bb354bb
Some games have junk audio sectors with a channel number of 255.
If these are not skipped, then they will play wrong file.
This was tested on "Blue's Clues : Blue's Big Musical" and
it fixed the missing audio there.
Taxi 2 is also said to be affected by this.
=> CDROM: Ignore sectors with channel number 255

libpcsxcore/psxinterpreter.c
This merges a fix for the interpreter from libretro's fork.
The fix is here : libretro/pcsx_rearmed#530
Notaz recommended me to disable it for ARM platforms as it only happens for Amidog's CPU test and could slow it down there.
Without the DIV fix, this will make Amidog's CPU test crash the emulator.
=> psxinterpreter: Merge DIV interpreter fix from libretro's fork

libpcsxcore/cdrom.c
As i noted in https://github.com/notaz/pcsx_rearmed/pull/207#issuecomment-907510653,
my last PR broke Gundam Battle Assault 2 for the PAL version. (also affects the NTSC version if booted in PAL mode)
The cdlpause changes from Mednafen were intended so i could possibly look into fixing Rise 2/Bedlam (as Duckstation code implemented async reading also, so it's kind of all over the place) but for now, they are not quite accurate and i have been told duckstation's "magic numbers" were gotten from hardware tests.
(which i assume, [were noted down here](https://github.com/JaCzekanski/ps1-tests/blob/master/cdrom/timing/psx.log))
Until Mednafen looks around it, let's just use a simplier fix. (and yes, i've tried it with all the 3 games that were noted down in the comments and they all work fine …
=> Fix regression with CdlPause

libpcsxcore/cdrom.c, libpcsxcore/cdrom.h
This is taken from the way Mednafen implemented it.
https://github.com/libretro-mirrors/mednafen-git/blob/563b72e377fa8284559df4df0271108d4935c9f1/src/psx/cdc.cpp#L941
See the discussions here :
https://github.com/gameblabla/pcsx4all_rs97_rg350/issues/3
https://github.com/libretro/pcsx_rearmed/issues/229
The PR is probably not big endian safe right now so if i got it wrong, tell me.
This properly fixes the freeze issue in Fantastic Pinball Kyuutenkai.
=> Implement fix from Mednafen for Fantastic Pinball Kyuutenkai.

Makefile, frontend/menu.c, libpcsxcore/misc.c, libpcsxcore/new_dynarec/new_dynarec.c, libpcsxcore/psxcounters.c, libpcsxcore/psxmem.c, libpcsxcore/psxmem.h, libpcsxcore/r3000a.c, libpcsxcore/r3000a.h
This fixes building on GCC10 and ARM. (the GCC10 fix is based upon libretro's fix : https://github.com/libretro/pcsx_rearmed/pull/466.
Note that in my previous HLE patch, i forgot to export psxNULL so it was failling to compile it... Oops.
=> ARM build fixes. (Fixes building on ARM/GCC10)

libpcsxcore/misc.c
This also fix the detection of some obscure game.
Both fixes were taken from another fork of PCSX4ALL and PCSX Reloaded.
I was able to confirm it fixed the issue for Wild Arms USA.
The PCSX Reloaded fix mentioned that notaz broke the obscure games... : P
https://github.com/gameblabla/pcsxr/commit/c305bd479c0d4233bf4106401e0b64cd5f12be0b
Here's the original fix from PCSX4ALL :
https://github.com/jdgleaver/RG350_pcsx4all/commit/c96751d43ff6373dda49b87a296df7cafffa5461
There is probably a cleaner way though.
=> Fix detection of some CDs such as Wild Arms USA detected as a PAL game.

configure, frontend/main.c, frontend/menu.c, libpcsxcore/new_dynarec/emu_if.c, libpcsxcore/psxbios.c, libpcsxcore/psxcommon.h, libpcsxcore/psxhw.c, libpcsxcore/psxinterpreter.c, libpcsxcore/psxmem.c, libpcsxcore/r3000a.c, libpcsxcore/r3000a.h
See (Redux) :
https://github.com/grumpycoders/pcsx-redux/commit/1923ce54ef585beba3a948d50f8c30161102312c
See original icache implementation (mirror of PCSX Reloaded):
https://github.com/gameblabla/pcsxr
Without icache emulation, F1 2001 will greatly misbehave :
if you accelerate, the car will go around like crazy.
With icache emulation, it works as intended.
Our code is slightly different from theirs as i found out that having the icache arrays in psxregs would cause crashes.
Instead, i'm taking them out of there and only allocating them on the heap (due to their great size).
I'm open for suggestions. For example, should i put writeok in Psxregs or out of it ?
**EDIT**: I should point out this doesn't add icache emulation for the ARM dynarec. That will need to be done by someone else.
=> Icache emulation from PCSX Redux + Senquack changes from PCSX4ALL

libpcsxcore/psxhw.c
For some reason, the game detects that a link cable is plugged in
and disables the local multiplayer as a result.
Thanks @sony for fixing the issue in their PS Classic branch, a simpler fix is done here instead.
**Unfixed**
**Fixed**
=> Fix for Armored Core misdetecting a Link cable being detected

libpcsxcore/psxcounters.c
As done by Duckstation
https://github.com/stenzek/duckstation/blob/bbcf1c67d1aefd5de9cdc9c158f92bc7aaecaa63/src/core/gpu.h#L56
Mednafen also sets it to 314 and has some more explanation about it :
https://github.com/libretro-mirrors/mednafen-git/blob/1899500078169e787f86eb5302a3f35abdaa8764/src/psx/gpu.cpp#L44
=> One more on odd lines for PAL (HSYNC)

libpcsxcore/cdriso.c, libpcsxcore/cdrom.c, libpcsxcore/cdrom.h, libpcsxcore/plugins.h
There's a game, PoPoLoCrois Monogatari II, that unfortunately locks up during the intro screen.
I should have known that code was wrong as Mednafen did not have anything like that in their code either, hence the confusion.
Their fix however still don't include the Driver fix so the game would still crash if we don't have the "+ Seektime".
To be honest, i'm not sure why the PCSX Reloaded team did it this way...
In any case, i adjusted it so it doesn't mess up the audio for Driver's titlescreen and doesn't crash in Worms Pinball either.
Seems like setting it to 100000 was not enough for that game.
I noticed the fastword and FastBackward were not being used in any way.
Looked at Mednafen and all they do is just adjust the cursector
and make sure that fastword & backword trigger the …
=> Merge several fixes from PCSX Redux and adjust delay for SetLocPending.

libpcsxcore/cdrom.c
A regression was introduced by the CDROM timings changes
https://github.com/notaz/pcsx_rearmed/commit/dc0ee8d424293ea687a137ec1ca0440f88a1e5a5
This was done to fix some games such as :
- Crash Team Racing's intro music cutting off too soon
- FF8 Lunar Cry FMV freeze (Disc 3)
- Worms Pinball not booting
- Xenogears (Deus fight)
However for whatever reason, this also caused ADPCM speech samples
in Castlevania Symphony of the Night to stutter.
This could be caused by another underlying issue however.
Here are the commands being run by Castlevania for speech samples :
```
CD1 write: 1 (CdlNop)
CD1 write: 1 (CdlNop)
CD1 write: 9 (CdlPause)
CD1 write: e (CdlSetmode) Param[1] = { c8,}
CD1 write: 1 (CdlNop)
CD1 write: d (CdlSetfilter) Param[2] = { b, 6,}
CD1 write: 1 (CdlNop)
CD1 write: 2 …
```
=> Hack fix stutter before speech samples in Castlevania Symphony of the Night

libpcsxcore/cdrom.c
So far,
i could only find Simple 1500 Series Vol. 31 - The Sound Novel to be affected by this.
In Duckstation, this was causing extra delays without it.
However in our case, this doesn't seem to be the case and i couldn't find much find about it.
I moved it to cdrInterrupt as there was no error handling in cdrWrite1
and we are supposed to return "Invalid arg" upon the check being met.
https://github.com/stenzek/duckstation/commit/c962e9899d75e95646bedd1d03e3052e634ec92f#diff-0077a49e8c9a58eb9c85becc595ff6cf27e560f1728116423a5aaa52b8b30e89
I don't think i'm doing anything wrong but let me know, it's kind of iffy.
=> Move CdlSetLoc to CdrInterrupt and return invalid arg error

libpcsxcore/cdrom.c
This was added back in 2013 or so in PCSX Rearmed
and according to some tests against Tomb Raider 1 (which is affected by the GetLocP code),
it works properly without this hack.
So let's just remove it as we are now doing it properly. (Besides, Duckstation and mednafen don't have this hack)
https://github.com/libretro-mirrors/mednafen-git/blob/master/src/psx/cdc.cpp#L2133
=> Remove CdlGetlocP hack.

libpcsxcore/cdrom.c
My bad guys.
Thanks to https://github.com/CometHunter92/pcsx_rearmed/commit/242b473df8b88101a013b639604b06d4418fad47 for noticing the issue, i had correctly fixed this in my PR for redux but not this one.
=> Fix silly typo mistake for CDROM pause/resume fix for DOA.

libpcsxcore/cdrom.c
Merge PCSX Redux fix.
It can be found here : https://github.com/johnbaumann/pcsx-redux/commit/9ab09443ff44f0429185881bb89309f5aea36eb0
This is what he had to say about it :
"So, this commit works around/fixes two issues with loading unirom.
There's a fix for logging invalid commands which should be pretty straight forward. The other change is around the FIFO flag.
Not really experienced with debugging/verifying this sort of thing so not feeling really confident the change is "right", though every game I've tried so far still seem to work as expected.
There's still something going on with not having an iso mounted that I haven't quite nailed down. Even having the iso mounted with "lid open" gives a bootable result. Feel like I'm going in circles a bit for something that might be an easy …
=> clear Index0 data FIFO flag

plugins/gpu_unai/gpulib_if.cpp
f23b103c8248c10855949bfb2185b6b10d4f0457 was missing changes to gpu_unai/gpulib_if.cpp
=> Fix building gpu_unai on armv6

plugins/dfsound/registers.c, plugins/dfsound/reverb.c, plugins/dfsound/spu.h, plugins/dfsound/xa.c
Without this fix, the BIOS' music is missing on big-endian systems.
Original fix by @xjsxjs197.
=> dfsound: Fix issues on big-endian systems

libpcsxcore/cdrom.c
=> cdrom: rename mode constants to defineds

libpcsxcore/database.c
Without it, the Retry/Quit menu when you lose a race is invisible.
Fixes https://github.com/libretro/pcsx_rearmed/issues/776.
=> add Bomberman: Fantasy Race to database for hack "(GPU) slow linked list walking"

libpcsxcore/database.c
Fixes issue https://github.com/libretro/pcsx_rearmed/issues/837
=> more timing hacks: fix jump command on Power Rangers - Lightspeed Rescue

libpcsxcore/database.c
According to SuperrSonic, the game's jumping command does not work if the game FPS is over 30.
At 280, on level 3 has audio stutters. Needs more testing.
SuperrSonic found 310 ideal to maintain the emulation at full speed, at the cost of the game dropping more frames, this allowed jumping to always work and keep the sound stutter free, as it was tested the entire game this way.
Credit to @SuperrSonic for this fix.
Read this message for further info: https://github.com/libretro/pcsx_rearmed/issues/837#issuecomment-2189745153
=> Update timing (override) hack for Power Rangers: Lightspeed Rescue (SuperrSonic)

configure, plugins/gpu-gles/Makefile, plugins/spunull/Makefile
also don't redefine PIC in Makefiles
I've had `reloc type` error, when used with gcc compiled with -fPIE as def cflag otherwise on armv5
=> configure: unset `PIC` cflag for plugins if not used

Makefile, configure, frontend/menu.c
also don't build shared object for built-in one
=> frontend/menu: omit already build-in GPU in external plugins

frontend/menu.c, frontend/plugin_lib.c, readme.txt
I'm trying to make [BIOS/Plugins] sub-menu less overwhelming
the `menu_loop_plugin_gpu_peopsgl` becomes obsolete now but the rest of gpu loops will be legit after: https://github.com/notaz/pcsx_rearmed/pull/365
P.S. Moreover I tried to update gpu descrip. header dynamicly, but it will only work when moving "Configure external GPU" menu entry to another sub-menu, so better to leave it as it is.
=> frontend/menu: only display sel. GPU plug setting

Makefile, configure, frontend/menu.c
For that reusing existing C macros (to much of them), and adding new configure variable HAVE_NEON_GPU. The peops & unai are build/supported either way.
Will try to close plugin stuff with this one.
=> frontend/menu: display descrip. only for supported GPU plugins

configure, frontend/menu.c
Personally I've not seen staticly linked build loading dynamicly shared objects, also some libc even don't have dlfcn.h implemented in them (not to say anything about Windows although there are [workarounds](https://github.com/dlfcn-win32/dlfcn-win32)).
`tslib` depends on dlfcn so we have to disable it when `have_dynamic=no` (added small warning in configure echo)
This fixes build on our static uClibc toolchain with `configure --disable-dynamic`, but it should go after https://github.com/notaz/pcsx_rearmed/pull/367 (sorry for being ahead of myself).
=> frontend: disable dl func. support on static builds

frontend/menu.c
`error: a label can only be part of a statement and a declaration is not a statement`
I've unintenionally broke shared build on older gcc (e.g 9.4.0), so we either add an empty statement after label or move declaration down (_mea culpa_).
=> frontend/menu: label can only go with statement

frontend/menu.c
mandatory for 320x240 disp, also present in libretro port.
I've notice also `pixel_skip` opt. but didn't notice any performance gain so not sure about it's usability and not adding as such.
=> frontend/menu: add "Downscale Hi-Res" option
